site_name: cont
repo_url: https://github.com/farkon00/cont
theme:
  name: readthedocs 
nav:
  - Home: index.md
  - Learn:
      - 'learn/index.md'
      - 'learn/01-quick-start.md'
      - 'learn/02-basic-operation.md'
      - 'learn/03-loops-and-conditions.md'
      - 'learn/04-binds.md'
      - 'learn/05-procedures.md'
      - 'learn/06-variables.md'

